export const REACT_APP_ENVIRONMENT = "PROD";
let PROD_OBJ = {};
// PROD_OBJ["MAIN_BASE_API_URL"] = "http://dndrepo.gh.internal.vodafone.com";
// PROD_OBJ["MAIN_BASE_API_URL"] = "http://";

PROD_OBJ["BASE_API_URL_AUTH"] = "https://pythonrestapibooks.herokuapp.com/login"



PROD_OBJ["BASE_API_URL"] =  "/r/";
PROD_OBJ["BASE_API_URL_VERSION"] = PROD_OBJ["BASE_API_URL"] + "api/v1/"; 
PROD_OBJ["BASE_API_URL_REGULAR_USER"] = PROD_OBJ["BASE_API_URL_VERSION"] + "authenticate"; 
// PROD_OBJ["BASE_API_URL_ADMIN_USER"] = PROD_OBJ["BASE_API_URL_VERSION"] + "authenticateAdmin";
PROD_OBJ["BASE_API_URL_ADMIN_USER"] = PROD_OBJ["BASE_API_URL_VERSION"]+"authenticateAdmin";
PROD_OBJ["API_UPDATE_USER"] = PROD_OBJ["BASE_API_URL_VERSION"] + "updateUser"; 
PROD_OBJ["API_CREATE_USER"] = PROD_OBJ["BASE_API_URL_VERSION"] + "createUser";
PROD_OBJ["API_UPDATE_USER"] = PROD_OBJ["BASE_API_URL_VERSION"] + "updateUser";
PROD_OBJ["API_GET_USER"] = PROD_OBJ["BASE_API_URL_VERSION"] + "getUsers"; // chec
PROD_OBJ["API_CREATE_CHANNEL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "createChannel";
PROD_OBJ["API_GET_CHANNEL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "getChannels";
PROD_OBJ["API_UPDATE_CHANNEL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "updateChannel"; 

PROD_OBJ["API_SEND_MAIL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "sendmail";

PROD_OBJ["API_CREATE_SUBSCRIPTION"] = PROD_OBJ["BASE_API_URL_VERSION"] + "createSubscription";
PROD_OBJ["API_GET_SUBSCRIPTION"] = PROD_OBJ["BASE_API_URL_VERSION"] + "getAllSubscriptions"; 
PROD_OBJ["API_GET_SUBSCRIPTION_BY_MSISDN"] = PROD_OBJ["BASE_API_URL_VERSION"] + "getSubscriptionByMsisdn/";
PROD_OBJ["API_GET_SUBSCRIPTION_TYPE"] = PROD_OBJ["BASE_API_URL_VERSION"] + "subscription/types";
PROD_OBJ["API_GET_SUBSCRIPTION_FILTRATION"] = PROD_OBJ["BASE_API_URL_VERSION"] + "subscriptions/filtration";

PROD_OBJ["API_CREATE_CAMPAIGN"] = PROD_OBJ["BASE_API_URL_VERSION"] + "createCampaign";
PROD_OBJ["API_GET_CAMPAIGN"] = PROD_OBJ["BASE_API_URL_VERSION"] + "getCampaigns"; 
PROD_OBJ["API_UPDATE_CAMPAIGN"] = PROD_OBJ["BASE_API_URL_VERSION"] + "updateCampaign";
PROD_OBJ["API_CHANGE_CAMPAIGN_STATUS"] = PROD_OBJ["BASE_API_URL_VERSION"] + "changeCampaignStatus/"; // /{id}/{status}

PROD_OBJ["API_GET_SUBSCRIPTION_TOTAL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "subscribers/total/count";
PROD_OBJ["API_GET_CHANNEL_TOTAL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "channel/total/count";
PROD_OBJ["API_GET_CAMPAIGN_TOTAL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "campaigns/total/count";
PROD_OBJ["API_GET_USER_TOTAL"] = PROD_OBJ["BASE_API_URL_VERSION"] + "users/total/count";


export const PROD = PROD_OBJ;